/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v2_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pedir Link */
        post: operations["pedir_link_api_v2_auth_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/entrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confirmar Entrada */
        get: operations["confirmar_entrada_api_v2_auth_entrar_get"];
        put?: never;
        /** Entrar */
        post: operations["entrar_api_v2_auth_entrar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/auth/sair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sair */
        post: operations["sair_api_v2_auth_sair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/licitacoes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_v2_licitacoes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/licitacoes/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe */
        get: operations["detalhe_api_v2_licitacoes__pid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/evidencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidencias */
        get: operations["evidencias_api_v2_evidencias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/precos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Precos */
        get: operations["precos_api_v2_precos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/resumo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumo */
        get: operations["resumo_api_v2_resumo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar */
        get: operations["listar_api_v2_alertas_get"];
        put?: never;
        /** Criar */
        post: operations["criar_api_v2_alertas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/alertas/{aid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Apagar */
        delete: operations["apagar_api_v2_alertas__aid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/conta/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram */
        post: operations["telegram_api_v2_conta_telegram_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/operador/saude": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saude */
        get: operations["saude_api_v2_operador_saude_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Arquivo */
        Arquivo: {
            /** Nome */
            nome: string;
            /** Url */
            url: string | null;
        };
        /** Conta */
        Conta: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Operador */
            operador: boolean;
            /** Csrf */
            csrf: string;
        };
        /** Contrato */
        Contrato: {
            /** Numero */
            numero: string | null;
            /** Fornecedor */
            fornecedor: string | null;
            /** Cnpj */
            cnpj: string | null;
            /** Valor */
            valor: number | null;
            /** Assinatura */
            assinatura: string | null;
            /** Vigencia Inicio */
            vigencia_inicio: string | null;
            /** Vigencia Fim */
            vigencia_fim: string | null;
        };
        /** Fase */
        Fase: {
            /** Rotulo */
            rotulo: string | null;
            /** Inicio */
            inicio: string | null;
            /** Fim */
            fim: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Item */
        Item: {
            /** Descricao */
            descricao: string | null;
            /** Quantidade */
            quantidade: number | null;
            /** Unidade */
            unidade: string | null;
            /** Valor Estimado */
            valor_estimado: number | null;
        };
        /** LicitacaoDetalhe */
        LicitacaoDetalhe: {
            /** Id */
            id: number;
            /** Fonte */
            fonte: string;
            /** Numero */
            numero: string | null;
            /** Objeto */
            objeto: string | null;
            /** Modalidade */
            modalidade: string | null;
            /** Orgao */
            orgao: string | null;
            /** Abertura */
            abertura: string | null;
            /**
             * Situacao
             * @enum {string}
             */
            situacao: "aberta" | "andamento" | "suspensa" | "encerrada" | "cancelada" | "desconhecida";
            /** Rotulo */
            rotulo: string | null;
            /** Dias Para Abertura */
            dias_para_abertura: number | null;
            /** Publicacao */
            publicacao: string | null;
            /** Criterio */
            criterio: string | null;
            /** Homologacao */
            homologacao: string | null;
            link_origem?: components["schemas"]["LinkOrigem"] | null;
            /** Fases */
            fases: components["schemas"]["Fase"][];
            /** Contratos */
            contratos: components["schemas"]["Contrato"][];
            /** Vencedores */
            vencedores: components["schemas"]["Vencedor"][];
            /** Itens */
            itens: components["schemas"]["Item"][];
            /** Arquivos */
            arquivos: components["schemas"]["Arquivo"][];
        };
        /** LicitacaoResumo */
        LicitacaoResumo: {
            /** Id */
            id: number;
            /** Fonte */
            fonte: string;
            /** Numero */
            numero: string | null;
            /** Objeto */
            objeto: string | null;
            /** Modalidade */
            modalidade: string | null;
            /** Orgao */
            orgao: string | null;
            /** Abertura */
            abertura: string | null;
            /**
             * Situacao
             * @enum {string}
             */
            situacao: "aberta" | "andamento" | "suspensa" | "encerrada" | "cancelada" | "desconhecida";
            /** Rotulo */
            rotulo: string | null;
            /** Dias Para Abertura */
            dias_para_abertura: number | null;
        };
        /** LinkOrigem */
        LinkOrigem: {
            /** Url */
            url: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "processo" | "edital" | "lista";
            /** Rotulo */
            rotulo: string;
        };
        /** NovoAlerta */
        NovoAlerta: {
            /** Palavras */
            palavras: string[];
        };
        /** PaginaLicitacoes */
        PaginaLicitacoes: {
            /** Itens */
            itens: components["schemas"]["LicitacaoResumo"][];
            /** Total */
            total: number;
            /** Pagina */
            pagina: number;
            /** Por Pagina */
            por_pagina: number;
            /** Facetas */
            facetas: {
                [key: string]: {
                    [key: string]: number;
                };
            };
        };
        /** PedidoLink */
        PedidoLink: {
            /** Email */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vencedor */
        Vencedor: {
            /** Item */
            item: string | null;
            /** Fornecedor */
            fornecedor: string | null;
            /** Cnpj */
            cnpj: string | null;
            /** Quantidade */
            quantidade: number | null;
            /** Valor */
            valor: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_api_v2_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conta"];
                };
            };
        };
    };
    pedir_link_api_v2_auth_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmar_entrada_api_v2_auth_entrar_get: {
        parameters: {
            query?: {
                t?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entrar_api_v2_auth_entrar_post: {
        parameters: {
            query?: {
                t?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sair_api_v2_auth_sair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listar_api_v2_licitacoes_get: {
        parameters: {
            query?: {
                q?: string;
                situacao?: ("aberta" | "andamento" | "suspensa" | "encerrada" | "cancelada" | "desconhecida")[];
                fonte?: string[];
                modalidade?: string | null;
                abertura_de?: string | null;
                abertura_ate?: string | null;
                ordem?: ("relevancia" | "prazo" | "abertura") | null;
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaLicitacoes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalhe_api_v2_licitacoes__pid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicitacaoDetalhe"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidencias_api_v2_evidencias_get: {
        parameters: {
            query: {
                ids: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    precos_api_v2_precos_get: {
        parameters: {
            query: {
                q: string;
                tipo?: "contrato" | "item";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumo_api_v2_resumo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listar_api_v2_alertas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    criar_api_v2_alertas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovoAlerta"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apagar_api_v2_alertas__aid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                aid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    telegram_api_v2_conta_telegram_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    saude_api_v2_operador_saude_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
